name: Challenge Deployment
on: push

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  deploy:
    name: deploy-challenge
    runs-on: ubuntu-latest
    needs: cancel

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run container
        run: docker-compose up -d

      - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
        with:
          timeout: 1h
          port: 4000
          ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
